### ISSUE TITLE
Add proxies

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_qgis_plugin#12]
Add proxies and all related information to the proxy setup file. The needed information is at least:
- Proxy name
- Related mineral system type
- Importances per scale
- Workflow steps needed for calculation / UI name that allows for the production of the proxy
- Keywords / categories

**Comment by msorvoja** [comment]
Other mineral systems than IOCG lack proxy names in the "Mineral Systems vectors.xlsx" file.

**Comment by msorvoja** [comment]
Proxy names are missing from other mineral systems than IOCG in "Mineral Systems vectors.xlsx" file.
