### ISSUE TITLE
Distance computation takes a long time

### ISSUE THREAD

**Issue by jtpesone** [GispoCoding/eis_qgis_plugin#145]
Description
Distance computation (in wizard and processing algorithms) takes much longer than in ArcGIS (3 sec vs 1 min)

Repro steps
Follow the steps for issue #144 for computing the distance.

Expected behavior
Computation time should be closer to ArcGIS's

Desktop:
 - Plugin: 0.2
 - QGIS 3.28.6
 - Python: 3.10
 - OS: Windows 10

**Comment by nmaarnio** [comment]
Closing this as optimizing the algorithm is done in EIS Toolkit and issue for that exists.
