### ISSUE TITLE
Raster dist to anomaly not Running

### ISSUE THREAD

**Issue by jtpesone** [GispoCoding/eis_qgis_plugin#147]
Description
When a proxy is being generated, for instance distance to Magnetic highs, and the distance computation does not do anything when pressing the Run button.

Repro Steps (wizard)
1. In the wizard Mineral system proxies page, select IOCG Mineral system and Study scale "Regional"
2. On the Depositional processes proxy tab, press the Process button of the first proxy Magnetic highs
3.  Skip the interpolation and press Next
4. Provide to the distance computation a one band tiff raster, and press Run. Nothing happens. Does not matter whether the output is written on disk or in a temporary file.

Expected behavior
A distance raster should be generated

Desktop:
- Plugin: 0.2
- QGIS 3.28.6
- Python: 3.10
- OS: Windows 10

**Comment by nmaarnio** [comment]
Distance to anomaly is not implemented yet even in the processing toolbox, so it won't work in the Wizard either.

**Comment by nmaarnio** [comment]
Closing this as Distance to anomaly can now be run in Wizard
