### ISSUE TITLE
Distance computation

### ISSUE THREAD

**Issue by jtpesone** [GispoCoding/eis_qgis_plugin#163]
**Describe the bug**
In the EIS Processing algorithms: Vector processing - Distance computation tool, the Base raster is an optional input parameter. However, if Base raster is not given, the tool produces an error.

**Expected behavior**
Base raster should be an obligatory input.

 - Plugin: 0.3.7
 - QGIS 3.28.6
 - Python: 3.10
 - OS: Windows 10

**Comment by nmaarnio** [comment]
Did you use set `Pixel size` and `Raster extent`?` They need to be set of course, when not using base raster. I was able to just now run the tool without base raster.
