### ISSUE TITLE
Random forest classifier

### ISSUE THREAD

**Issue by jtpesone** [GispoCoding/eis_qgis_plugin#166]
**Describe the bug**
Random forest classifier run from the EIS Processing algorithms with five input data sets and the base raster, available from the signee. Default computation parameters. Training points was the ...Occ2 occurrences file in the EIS project's IOCG dataset. Produces an error:
Run failed. Error: invalid literal for int() with base 10: '30%") '

**Desktop (please complete the following information):**
 - Plugin: 0.3.7
 - QGIS: 2.28.6
 - Python:  3.10
 - OS: Windows 10

**Comment by nmaarnio** [comment]
This new release hopefully fixes this: https://github.com/GispoCoding/eis_qgis_plugin/releases/tag/v0.3.9

**Comment by nmaarnio** [comment]
Closing as issue is fixed.
