### ISSUE TITLE
Add Local Moran's I processing algorithm

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_qgis_plugin#62]
Note: CLI function for Local Moran's I should be first implemented In EIS Toolkit

**Comment by nmaarnio** [comment]
You could start working on this when you are finished with Surface derivatives @lehtonenp . Check PR https://github.com/GispoCoding/eis_toolkit/pull/320 in EIS Toolkit and the corresponding branch for the CLI implementation. Local Moran's I and its CLI function have not been merged to master yet, but they should not undergo any changes in the parameterspace, and therefore it is possible to start working on this.

**Comment by lehtonenp** [comment]
> You could start working on this when you are finished with Surface derivatives @lehtonenp . Check PR [GispoCoding/eis_toolkit#320](https://github.com/GispoCoding/eis_toolkit/pull/320) in EIS Toolkit and the corresponding branch for the CLI implementation. Local Moran's I and its CLI function have not been merged to master yet, but they should not undergo any changes in the parameterspace and be merged soon, and therefore it is possible to start working on this.

@nmaarnio, I will check the PR when I am finished with Surface derivatives.
