### ISSUE TITLE
Add Distance to anomaly processing algorithm

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_qgis_plugin#63]
Note: CLI function for Distance to anomaly should be first implemented In EIS Toolkit.

**Comment by lehtonenp** [comment]
@nmaarnio, is this ready for work? I can start creating the plugin tool if so.

**Comment by nmaarnio** [comment]
You can start working on this if you want, but just note that the Distance to anomaly tool itself has not been merged yet and the CLI function hasn't yet been started. But I don't think the tool will see noticeable changes in the interface so it's possible to start already.

**Comment by lehtonenp** [comment]
> You can start working on this if you want, but just note that the Distance to anomaly tool itself has not been merged yet and the CLI function hasn't yet been started. But I don't think the tool will see noticeable changes in the interface so it's possible to start already.

Ok. Thank you for the information. I will create a plugin tool similar to the Distance to anomaly toolkit function and adjust it as needed.
