### ISSUE TITLE
Add Surface derivatives processing algorithm

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_qgis_plugin#65]

**Comment by nmaarnio** [comment]
Since `surface_derivatives_cli` function has been implemented in EIS Toolkit CLI, you could start working on this one first @lehtonenp and others.

**Comment by lehtonenp** [comment]
@nmaarnio, I created a branch for this issue and made an initial implementation. I would like to hear feedback regarding naming conventions of the branch and whether the code is adequate. The branch is linked to this issue.

**Comment by nmaarnio** [comment]
Please make a (draft) PR, it's easier to take a look that way.

Branches can be created directly from the issue in GitHub and the name becomes the issue name prefixed with the issue number. This is recommended and follows EIS Toolkit convention. But it is not a strict thing so no worries.
