### ISSUE TITLE
Fix Create constant raster

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_qgis_plugin#92]
Create constant raster does not work currently. Should be matched to the toolkit CLI definition.

**Comment by lehtonenp** [comment]
@nmaarnio, any help with making the target epsg optional and use the project's epsg if it is not chosen? Should I override the `processAlgorithm()`?

**Comment by nmaarnio** [comment]
I think following the logic of QGIS's own Create constant raster layer is a good idea. So CRS is not optional. Overall our algorithm will be quite identical to that one, with the exception that we don't expose number type definition to users.
